<template>
  <div>
    <md-autocomplete2 v-model="selectedCountry" :md-options="countries">
      <label>Country</label>
    </md-autocomplete2>
    <md-autocomplete2 v-model="selectedIndustry" :md-options="industries">
      <label>Industry</label>
    </md-autocomplete2>

    <md-autocomplete2 v-model="selectedEmployee" :md-options="employees" md-dense>
      <label>Employees</label>
    </md-autocomplete2>
  </div>
</template>

<script>
  export default {
    name: 'AutocompleteStatic',
    data: () => ({
      selectedCountry: null,
      selectedEmployee: null,
      selectedIndustry: null,
      countries: [
        'Algeria',
        'Argentina',
        'Brazil',
        'Canada',
        'Italy',
        'Japan',
        'United Kingdom',
        'United States'
      ],
      employees: [
        'Jim Halpert',
        'Dwight Schrute',
        'Michael Scott',
        'Pam Beesly',
        'Angela Martin',
        'Kelly Kapoor',
        'Ryan Howard',
        'Kevin Malone',
        'Creed Bratton',
        'Oscar Nunez',
        'Toby Flenderson',
        'Stanley Hudson',
        'Meredith Palmer',
        'Phyllis Lapin-Vance'
      ],
      industries: [
        "Adventure sports",
        "Adventure sports center",
        "Aerial sports center",
        "Amphitheater",
        "Amphitheatre",
        "Amusement center",
        "Amusement park",
        "Amusement park ride",
        "Amusement ride",
        "Amusement ride supplier",
        "Animal park",
        "Aquarium",
        "Aquarium shop",
        "Aquatic center",
        "Arcade",
        "Archaeological museum",
        "Army museum",
        "Art museum",
        "Athletic park",
        "Ballpark",
        "Ballroom",
        "Batting cage center",
        "Bouncy castle hire",
        "Bowling alley",
        "Bowling club",
        "Bowling supply shop",
        "Canoe & kayak rental service",
        "Canoe & kayak store",
        "Car racing track",
        "Children's amusement center",
        "Children's museum",
        "Cinema",
        "City park",
        "Concert hall",
        "Concert venue",
        "Conservation park",
        "Dinner theater",
        "Disc golf course",
        "Disney ride",
        "Disneyland attraction",
        "Drama theater",
        "Drive-in movie theater",
        "Escape room center",
        "Go-kart track",
        "Golf",
        "Golf cart dealer",
        "Golf club",
        "Golf course",
        "Golf facility",
        "Handicraft museum",
        "Heritage museum",
        "High ropes course",
        "Hiking area",
        "Historical place museum",
        "History museum",
        "Hockey rink",
        "Horse riding school",
        "Horseback riding service",
        "Ice skating",
        "Ice skating club",
        "Ice skating rink",
        "IMAX theater",
        "Indoor arena",
        "Indoor cycling",
        "Indoor golf course",
        "Indoor playground",
        "Indoor swimming pool",
        "Laser tag center",
        "Leisure centre",
        "Local history museum",
        "Memorial park",
        "Miniature golf course",
        "Modern art museum",
        "Movie theater",
        "Movie theatre",
        "Multi-purpose stadium",
        "Museum",
        "Museum of space history",
        "Museum of zoology",
        "National museum",
        "Natural history museum",
        "Off-road race track",
        "Open air museum",
        "Outdoor movie theater",
        "Paintball center",
        "Park",
        "Park & ride",
        "Playground",
        "Race track",
        "Racecourse",
        "Racetrack",
        "Rail museum",
        "Regional park",
        "Rock climbing",
        "Rock climbing gym",
        "Roller coaster",
        "Roller skating club",
        "Roller skating rink",
        "Skate sharpening service",
        "Skate shop",
        "Skateboard park",
        "Skateboard shop",
        "Skydiving center",
        "State park",
        "Technology museum",
        "Theater",
        "Theatre",
        "Theme park",
        "Toy museum",
        "Video arcade",
        "Water park",
        "Water skiing club",
        "Water sports equipment rental service",
        "Wax museum",
        "Zoo",
        "Zoo exhibit",
        "Zoological garden",
        "Zoological park"
      ]
    }),
  }
</script>
